version: "3.3"

services:

  postgresql:
    image: postgres:16.3-alpine
    container_name: "${PROJECT_NAME}_postgresql"
    restart: always
    environment:
      POSTGRES_DB: $POSTGRESQL_DATABASE
      POSTGRES_USER: $POSTGRESQL_USER
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRES_ROOT_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine
    container_name: "${PROJECT_NAME}_redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data